---

- block:
    - name: create local fonts directory
      file:
        path: "~{{ user }}/.local/share/fonts"
        state: directory
  become: yes
  become_user: "{{ user }}"

- block:
    - name: download nerd fonts to local fonts folder
      get_url:
        url: "{{ item  }}"
        dest: "~{{ user }}/.local/share/fonts/"
      with_items: "{{ terminal_customizations_nerd_fonts }}"
  become: yes
  become_user: "{{ user }}"

- name: refresh fonts cache
  shell: "fc-cache -fv"
  become: yes
  become_user: "{{ user }}"

  # fix for https://github.com/gnunn1/tilix/wiki/VTE-Configuration-Issue using option 2
# also, set font to SourceCodePro+Powerline+Awesome Regular for tmux powerline
- block:
    - name: copy tilix config template
      copy:
        src: tilix.dconf
        dest: /tmp/tilix.dconf
        force: yes

    - name: import modified tilix config
      shell: dconf load /com/gexperts/Tilix/ < /tmp/tilix.dconf
      ignore_errors: yes
  become: yes
  become_user: "{{ user  }}"

- block:
    - name: check if .tmux.conf exists in user's home dir
      stat:
        path: "~{{ user }}/.tmux.conf"
      register: dottmuxdotconf

    - name: backup .tmux.conf if it exists
      copy:
        src: "~{{ user }}/.tmux.conf"
        dest: "~{{ user }}/.tmux.conf.orig"
      when: dottmuxdotconf.stat.exists

    - name: copy the sample .tmux.conf file
      copy:
        src: .tmux.conf
        dest: "~{{ user }}/.tmux.conf"
        force: yes
  become: yes
  become_user: "{{ user }}"

...
